apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app 
spec:
  project: default
  source:
    repoURL: https://github.com/ErnestF3700/Kubernetes-Microservice-Deployment-Task-Part-3.git
    targetRevision: master
    path: nginx-app 
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-app 
  syncPolicy:
    automated:
      selfHeal: true 
      prune: true 
    syncOptions:
     - CreateNamespace=true 